wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.44.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723045688
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 98
      - 100
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 98
      - 100
      3:
      - 7
      - 13
      - 19
      - 23
      - 66
      4: 3.10.13
      5: 0.17.5
      6: 4.44.0
      8:
      - 5
      9:
        1: transformers_trainer
      13: linux-x86_64
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/grad_norm
      5: 1
      6:
      - 1
    - 1: train/learning_rate
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
d_model:
  desc: null
  value: 3072
n_heads:
  desc: null
  value: 24
n_layers:
  desc: null
  value: 32
expansion_ratio:
  desc: null
  value: 4
max_seq_len:
  desc: null
  value: 8192
vocab_size:
  desc: null
  value: 20486
resid_pdrop:
  desc: null
  value: 0.0
emb_pdrop:
  desc: null
  value: 0.0
learned_pos_emb:
  desc: null
  value: false
attn_config:
  desc: null
  value:
    alibi: true
    alibi_bias_max: 8
    attn_impl: torch
    attn_pdrop: 0.0
    attn_type: multihead_attention
    attn_uses_sequence_id: false
    clip_qkv: null
    prefix_lm: false
    qk_ln: false
    softmax_scale: null
    qk_gn: false
    sliding_window_size: -1
    rope: false
    rope_theta: 10000
    rope_impl: dail
    rope_dail_config:
      type: original
      pos_idx_in_fp32: true
      xpos_scale_base: 512
    rope_hf_config:
      type: no_scaling
      factor: 1.0
ffn_config:
  desc: null
  value:
    ffn_type: mptmlp
    fc_type: torch
init_device:
  desc: null
  value: cpu
logit_scale:
  desc: null
  value: null
no_bias:
  desc: null
  value: false
embedding_fraction:
  desc: null
  value: 1.0
norm_type:
  desc: null
  value: low_precision_layernorm
use_cache:
  desc: null
  value: false
init_config:
  desc: null
  value:
    emb_init_std: null
    emb_init_uniform_lim: null
    fan_mode: fan_in
    init_div_is_residual: true
    init_gain: 0.0
    init_nonlinearity: relu
    init_std: null
    name: kaiming_normal_
    verbose: 0
fc_type:
  desc: null
  value: torch
use_pad_tok_in_ffn:
  desc: null
  value: true
return_dict:
  desc: null
  value: true
output_hidden_states:
  desc: null
  value: false
output_attentions:
  desc: null
  value: false
torchscript:
  desc: null
  value: false
torch_dtype:
  desc: null
  value: bfloat16
use_bfloat16:
  desc: null
  value: false
tf_legacy_loss:
  desc: null
  value: false
pruned_heads:
  desc: null
  value: {}
tie_word_embeddings:
  desc: null
  value: true
chunk_size_feed_forward:
  desc: null
  value: 0
is_encoder_decoder:
  desc: null
  value: false
is_decoder:
  desc: null
  value: false
cross_attention_hidden_size:
  desc: null
  value: null
add_cross_attention:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
max_length:
  desc: null
  value: 20
min_length:
  desc: null
  value: 0
do_sample:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
num_beams:
  desc: null
  value: 1
num_beam_groups:
  desc: null
  value: 1
diversity_penalty:
  desc: null
  value: 0.0
temperature:
  desc: null
  value: 1.0
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
typical_p:
  desc: null
  value: 1.0
repetition_penalty:
  desc: null
  value: 1.0
length_penalty:
  desc: null
  value: 1.0
no_repeat_ngram_size:
  desc: null
  value: 0
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
bad_words_ids:
  desc: null
  value: null
num_return_sequences:
  desc: null
  value: 1
output_scores:
  desc: null
  value: false
return_dict_in_generate:
  desc: null
  value: false
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
remove_invalid_values:
  desc: null
  value: false
exponential_decay_length_penalty:
  desc: null
  value: null
suppress_tokens:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
architectures:
  desc: null
  value:
  - MPTForCausalLM
finetuning_task:
  desc: null
  value: null
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
tokenizer_class:
  desc: null
  value: null
prefix:
  desc: null
  value: null
bos_token_id:
  desc: null
  value: null
pad_token_id:
  desc: null
  value: null
eos_token_id:
  desc: null
  value: null
sep_token_id:
  desc: null
  value: null
decoder_start_token_id:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
_name_or_path:
  desc: null
  value: vinai/PhoGPT-4B
transformers_version:
  desc: null
  value: 4.44.0
auto_map:
  desc: null
  value:
    AutoConfig: vinai/PhoGPT-4B--configuration_mpt.MPTConfig
    AutoModelForCausalLM: vinai/PhoGPT-4B--modeling_mpt.MPTForCausalLM
model_type:
  desc: null
  value: vivid
verbose:
  desc: null
  value: 0
hidden_size:
  desc: null
  value: 3072
mm_vision_tower:
  desc: null
  value: openai/clip-vit-large-patch14
use_mm_proj:
  desc: null
  value: true
use_patch_importance_pooling:
  desc: null
  value: false
use_delta_transformer:
  desc: null
  value: false
mm_hidden_size:
  desc: null
  value: 1024
mm_vision_select_layer:
  desc: null
  value: -2
mm_use_im_start_end:
  desc: null
  value: true
sep_image_conv_front:
  desc: null
  value: false
tune_mm_mlp_adapter:
  desc: null
  value: true
freeze_mm_mlp_adapter:
  desc: null
  value: false
output_dir:
  desc: null
  value: model/output
overwrite_output_dir:
  desc: null
  value: false
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: false
do_predict:
  desc: null
  value: false
eval_strategy:
  desc: null
  value: 'no'
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 2
per_device_eval_batch_size:
  desc: null
  value: 1
per_gpu_train_batch_size:
  desc: null
  value: null
per_gpu_eval_batch_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
torch_empty_cache_steps:
  desc: null
  value: null
learning_rate:
  desc: null
  value: 0.002
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.95
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 1
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: cosine
lr_scheduler_kwargs:
  desc: null
  value: {}
warmup_ratio:
  desc: null
  value: 0.03
warmup_steps:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: model/output/runs/Aug07_15-47-25_89643f82eb0f
logging_strategy:
  desc: null
  value: steps
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 1
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: steps
save_steps:
  desc: null
  value: 2000
save_total_limit:
  desc: null
  value: 1
save_safetensors:
  desc: null
  value: true
save_on_each_node:
  desc: null
  value: false
save_only_model:
  desc: null
  value: false
restore_callback_states_from_checkpoint:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_cpu:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: null
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: true
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
ddp_backend:
  desc: null
  value: null
tpu_num_cores:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: []
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: null
dataloader_num_workers:
  desc: null
  value: 8
dataloader_prefetch_factor:
  desc: null
  value: null
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: vivid_stage1_phogpt4b
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: false
label_names:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: false
fsdp:
  desc: null
  value: []
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_v2: false
    xla_fsdp_grad_ckpt: false
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
accelerator_config:
  desc: null
  value:
    split_batches: false
    dispatch_batches: null
    even_batches: true
    use_seedable_sampler: true
    non_blocking: false
    gradient_accumulation_kwargs: null
deepspeed:
  desc: null
  value: vividbot/valley/configs/deepspeed/config_zero2.json
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: adamw_torch
optim_args:
  desc: null
  value: null
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value:
  - wandb
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: true
dataloader_persistent_workers:
  desc: null
  value: false
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
hub_private_repo:
  desc: null
  value: false
hub_always_push:
  desc: null
  value: false
gradient_checkpointing:
  desc: null
  value: true
gradient_checkpointing_kwargs:
  desc: null
  value: null
include_inputs_for_metrics:
  desc: null
  value: false
eval_do_concat_batches:
  desc: null
  value: true
fp16_backend:
  desc: null
  value: auto
evaluation_strategy:
  desc: null
  value: 'no'
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: null
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
dispatch_batches:
  desc: null
  value: null
split_batches:
  desc: null
  value: null
include_tokens_per_second:
  desc: null
  value: false
include_num_input_tokens_seen:
  desc: null
  value: false
neftune_noise_alpha:
  desc: null
  value: null
optim_target_modules:
  desc: null
  value: null
batch_eval_metrics:
  desc: null
  value: false
eval_on_start:
  desc: null
  value: false
eval_use_gather_object:
  desc: null
  value: false
sortish_sampler:
  desc: null
  value: false
predict_with_generate:
  desc: null
  value: false
generation_max_length:
  desc: null
  value: null
generation_num_beams:
  desc: null
  value: null
generation_config:
  desc: null
  value: null
cache_dir:
  desc: null
  value: null
freeze_backbone:
  desc: null
  value: true
tune_patch_pooling_matrix:
  desc: null
  value: false
force_fsdp:
  desc: null
  value: false
vis_lora:
  desc: null
  value: false
lora_lr:
  desc: null
  value: null
lora_save_strategy:
  desc: null
  value: 'no'
prediction_file_name:
  desc: null
  value: null
model_max_length:
  desc: null
  value: 8192
should_save:
  desc: null
  value: false
lora:
  desc: null
  value: false
model/num_parameters:
  desc: null
  value: 3994424320
